from .cozinheiros_model import Cozinheiro
from .degustadores_model import Degustador
from .editores_model import Editor
from .livros_model import Livro
from .restaurantes_model import Restaurante
from .categorias_model import Categoria
from .ingredientes_model import Ingrediente
from .empregados_model import Empregado
from .receitas_model import Receita
from .inclui_model import Inclui
from .ingredientes_receita_model import IngredienteReceita
from .restaurantes_cozinheiro_model import RestauranteCozinheiro
from .testa_model import Testa
from .possui_model import Possui
